### ISSUE TITLE
[ASK] How do you register a user?

### ISSUE THREAD

**Issue by amanve** [klfoulk16/personal_website#23]
Hi Kelly,
Was going through your project i need to understand how do you register a new user?
i'm not able to find any register route.!

**Comment by klfoulk16** [comment]
Hi,
 I’m a bit rough and haven’t looked at anything coding related in about a year, so forgive me fin my terminology is wrong...I added new users manually by opening a database connection and using SQL commands.

Best,
Kelly

________________________________
From: Aman Verma ***@***.***>
Sent: Sunday, April 3, 2022 11:09 AM
To: klfoulk16/personal_website ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [klfoulk16/personal_website] [ASK] How do you register a user? (Issue #23)


Hi Kelly,
Was going through your project i need to understand how do you register a new user?
i'm not able to find any register route.!

**Comment by amanve** [comment]
cool it was manual addition.! i was wondering were to find the route.
